USE MIMIC3;

BULK INSERT ADMISSIONS
FROM '/path/to/data/ADMISSIONS.csv'
WITH
(
    FIRSTROW = 2, -- as row is header
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0a',  -- '\n' does not work here, use '0x0a' instead
    TABLOCK,
	FORMAT = 'csv'
);

BULK INSERT CALLOUT
FROM '/path/to/data/CALLOUT.csv'
WITH
(
    FIRSTROW = 2, FIELDTERMINATOR = ',',  ROWTERMINATOR = '0x0a', TABLOCK, FORMAT = 'csv'
);

BULK INSERT CAREGIVERS
FROM '/path/to/data/CAREGIVERS.csv'
WITH
(
    FIRSTROW = 2, FIELDTERMINATOR = ',',  ROWTERMINATOR = '0x0a', TABLOCK, FORMAT = 'csv'
);

BULK INSERT CHARTEVENTS
FROM '/path/to/data/CHARTEVENTS.csv'
WITH
(
    FIRSTROW = 2, FIELDTERMINATOR = ',',  ROWTERMINATOR = '0x0a', TABLOCK, FORMAT = 'csv'
);

BULK INSERT CPTEVENTS
FROM '/path/to/data/CPTEVENTS.csv'
WITH
(
    FIRSTROW = 2, FIELDTERMINATOR = ',',  ROWTERMINATOR = '0x0a', TABLOCK, FORMAT = 'csv'
);

BULK INSERT D_CPT
FROM '/path/to/data/D_CPT.csv'
WITH
(
    FIRSTROW = 2, FIELDTERMINATOR = ',',  ROWTERMINATOR = '0x0a', TABLOCK, FORMAT = 'csv'
);

BULK INSERT D_ICD_DIAGNOSES
FROM '/path/to/data/D_ICD_DIAGNOSES.csv'
WITH
(
    FIRSTROW = 2, FIELDTERMINATOR = ',',  ROWTERMINATOR = '0x0a', TABLOCK, FORMAT = 'csv'
);

BULK INSERT D_ICD_PROCEDURES
FROM '/path/to/data/D_ICD_PROCEDURES.csv'
WITH
(
    FIRSTROW = 2, FIELDTERMINATOR = ',',  ROWTERMINATOR = '0x0a', TABLOCK, FORMAT = 'csv'
);

BULK INSERT D_ITEMS
FROM '/path/to/data/D_ITEMS.csv'
WITH
(
    FIRSTROW = 2, FIELDTERMINATOR = ',',  ROWTERMINATOR = '0x0a', TABLOCK, FORMAT = 'csv'
);

BULK INSERT D_LABITEMS
FROM '/path/to/data/D_LABITEMS.csv'
WITH
(
    FIRSTROW = 2, FIELDTERMINATOR = ',',  ROWTERMINATOR = '0x0a', TABLOCK, FORMAT = 'csv'
);

BULK INSERT DATETIMEEVENTS
FROM '/path/to/data/DATETIMEEVENTS.csv'
WITH
(
    FIRSTROW = 2, FIELDTERMINATOR = ',',  ROWTERMINATOR = '0x0a', TABLOCK, FORMAT = 'csv'
);

BULK INSERT DIAGNOSES_ICD
FROM '/path/to/data/DIAGNOSES_ICD.csv'
WITH
(
    FIRSTROW = 2, FIELDTERMINATOR = ',',  ROWTERMINATOR = '0x0a', TABLOCK, FORMAT = 'csv'
);

BULK INSERT DRGCODES
FROM '/path/to/data/DRGCODES.csv'
WITH
(
    FIRSTROW = 2, FIELDTERMINATOR = ',',  ROWTERMINATOR = '0x0a', TABLOCK, FORMAT = 'csv'
);

BULK INSERT ICUSTAYS
FROM '/path/to/data/ICUSTAYS.csv'
WITH
(
    FIRSTROW = 2, FIELDTERMINATOR = ',',  ROWTERMINATOR = '0x0a', TABLOCK, FORMAT = 'csv'
);

BULK INSERT INPUTEVENTS_CV
FROM '/path/to/data/INPUTEVENTS_CV.csv'
WITH
(
    FIRSTROW = 2, FIELDTERMINATOR = ',',  ROWTERMINATOR = '0x0a', TABLOCK, FORMAT = 'csv'
);

BULK INSERT INPUTEVENTS_MV
FROM '/path/to/data/INPUTEVENTS_MV.csv'
WITH
(
    FIRSTROW = 2, FIELDTERMINATOR = ',',  ROWTERMINATOR = '0x0a', TABLOCK, FORMAT = 'csv'
);

BULK INSERT LABEVENTS
FROM '/path/to/data/LABEVENTS.csv'
WITH
(
    FIRSTROW = 2, FIELDTERMINATOR = ',',  ROWTERMINATOR = '0x0a', TABLOCK, FORMAT = 'csv'
);

BULK INSERT MICROBIOLOGYEVENTS
FROM '/path/to/data/MICROBIOLOGYEVENTS.csv'
WITH
(
    FIRSTROW = 2, FIELDTERMINATOR = ',',  ROWTERMINATOR = '0x0a', TABLOCK, FORMAT = 'csv'
);

BULK INSERT NOTEEVENTS
FROM '/path/to/data/NOTEEVENTS.csv'
WITH
(
    FIRSTROW = 2, FIELDTERMINATOR = ',',  ROWTERMINATOR = '0x0a', TABLOCK, FORMAT = 'csv'
);

BULK INSERT OUTPUTEVENTS
FROM '/path/to/data/OUTPUTEVENTS.csv'
WITH
(
    FIRSTROW = 2, FIELDTERMINATOR = ',',  ROWTERMINATOR = '0x0a', TABLOCK, FORMAT = 'csv'
);

BULK INSERT PATIENTS
FROM '/path/to/data/PATIENTS.csv'
WITH
(
    FIRSTROW = 2, FIELDTERMINATOR = ',',  ROWTERMINATOR = '0x0a', TABLOCK, FORMAT = 'csv'
);

BULK INSERT PRESCRIPTIONS
FROM '/path/to/data/PRESCRIPTIONS.csv'
WITH
(
    FIRSTROW = 2, FIELDTERMINATOR = ',',  ROWTERMINATOR = '0x0a', TABLOCK, FORMAT = 'csv'
);

BULK INSERT PROCEDUREEVENTS_MV
FROM '/path/to/data/PROCEDUREEVENTS_MV.csv'
WITH
(
    FIRSTROW = 2, FIELDTERMINATOR = ',',  ROWTERMINATOR = '0x0a', TABLOCK, FORMAT = 'csv'
);

BULK INSERT PROCEDURES_ICD
FROM '/path/to/data/PROCEDURES_ICD.csv'
WITH
(
    FIRSTROW = 2, FIELDTERMINATOR = ',',  ROWTERMINATOR = '0x0a', TABLOCK, FORMAT = 'csv'
);

BULK INSERT SERVICES
FROM '/path/to/data/SERVICES.csv'
WITH
(
    FIRSTROW = 2, FIELDTERMINATOR = ',',  ROWTERMINATOR = '0x0a', TABLOCK, FORMAT = 'csv'
);

BULK INSERT TRANSFERS
FROM '/path/to/data/TRANSFERS.csv'
WITH
(
    FIRSTROW = 2, FIELDTERMINATOR = ',',  ROWTERMINATOR = '0x0a', TABLOCK, FORMAT = 'csv'
);
